# Generated by Django 3.2.5 on 2022-01-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='NAME',
            new_name='name',
        ),
    ]
